const express = require("express");
const c = require("../controllers/projectController");
const { protect } = require("../middleware/authMiddleware");
const router = express.Router();
router.get("/", c.getProjects);
router.get("/admin/all", protect, c.getAdminProjects);
router.get("/:idOrSlug", c.getProject);
router.post("/", protect, c.createProject);
router.put("/:id", protect, c.updateProject);
router.delete("/:id", protect, c.deleteProject);
module.exports = router;
