const express = require("express");
const c = require("../controllers/educationController");
const { protect } = require("../middleware/authMiddleware");
const router = express.Router();
router.get("/", c.getAllEducations);
router.get("/admin", protect, c.getAdminEducations);
router.get("/:id", c.getEducation);
router.post("/", protect, c.createEducation);
router.put("/:id", protect, c.updateEducation);
router.delete("/:id", protect, c.deleteEducation);
module.exports = router;
