const express = require("express");
const c = require("../controllers/experienceController");
const { protect } = require("../middleware/authMiddleware");
const router = express.Router();
router.get("/", c.getAllExperiences);
router.get("/admin", protect, c.getAdminExperiences);
router.get("/:id", c.getExperience);
router.post("/", protect, c.createExperience);
router.put("/:id", protect, c.updateExperience);
router.delete("/:id", protect, c.deleteExperience);
module.exports = router;
